In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df = pd.read_csv('water_quality_data.csv')
df.sample(10)

pH  Turbidity  Dissolved_Oxygen  Conductivity    Nitrate  \
410   7.498130   4.992099          7.664011    505.589762   4.263902   
1743  7.813315   1.720711          6.185409    332.727920   8.422365   
408   7.084207   6.060207         10.579710    306.654272   1.350857   
902   7.020121   1.204945          6.891467    339.883492   4.919882   
1759  7.920440   6.340165         10.472286    582.447931   2.953061   
1345  5.960571  10.751377          8.655034    625.511559   1.958654   
1580  7.140398   1.865385          8.241937    486.942272   3.814707   
692   6.243256  11.277477          9.184559    453.638183  10.345243   
1357  7.274263   4.127069          7.219450    520.235641   9.460621   
1579  6.432823   1.340164          7.364689    429.382416   4.636997   

      Phosphate  Temperature         TDS  Water_Quality  
410    0.430221    24.695570  494.620030              2  
1743   2.523839    16.729822  613.224189              1  
408    0.034490    26.591276  247.132540              1  
902    0.156934    21.649547  608.451878              1  
1759   0.589938    24.986571  901.591219              1  
1345   2.072057    20.623382  927.611042              0  
1580   1.513027    24.294921  390.319264              1  
692    0.449659    31.099716  523.605543              0  
1357   1.530916    27.208125  736.128646              1  
1579   1.887430    15.445170  183.564978              1

In [26]:
df.shape

(2000, 9)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   pH                2000 non-null   float64
 1   Turbidity         2000 non-null   float64
 2   Dissolved_Oxygen  2000 non-null   float64
 3   Conductivity      2000 non-null   float64
 4   Nitrate           2000 non-null   float64
 5   Phosphate         2000 non-null   float64
 6   Temperature       2000 non-null   float64
 7   TDS               2000 non-null   float64
 8   Water_Quality     2000 non-null   int64  
dtypes: float64(8), int64(1)
memory usage: 140.8 KB


In [28]:
df.columns

Index(['pH', 'Turbidity', 'Dissolved_Oxygen', 'Conductivity', 'Nitrate',
       'Phosphate', 'Temperature', 'TDS', 'Water_Quality'],
      dtype='object')

In [29]:
df.describe().T.round(2)

count    mean     std     min     25%     50%     75%  \
pH                2000.0    7.03    0.68    5.50    6.56    7.03    7.48   
Turbidity         2000.0    3.99    2.81    0.05    1.96    3.37    5.33   
Dissolved_Oxygen  2000.0    7.46    1.56    2.19    6.41    7.45    8.50   
Conductivity      2000.0  451.00  150.00  100.00  347.61  450.41  555.04   
Nitrate           2000.0    5.92    4.22    0.20    2.88    4.99    7.93   
Phosphate         2000.0    1.21    0.95    0.02    0.49    0.97    1.68   
Temperature       2000.0   25.08    4.99    8.32   21.71   25.06   28.56   
TDS               2000.0  500.59  198.72   50.00  363.79  501.24  636.83   
Water_Quality     2000.0    1.06    0.35    0.00    1.00    1.00    1.00   

                      max  
pH                   9.00  
Turbidity           27.22  
Dissolved_Oxygen    12.41  
Conductivity       981.61  
Nitrate             29.02  
Phosphate            5.86  
Temperature         40.00  
TDS               1220.57  
Water_Quality        2.00

In [30]:
df.isnull().sum()

pH                  0
Turbidity           0
Dissolved_Oxygen    0
Conductivity        0
Nitrate             0
Phosphate           0
Temperature         0
TDS                 0
Water_Quality       0
dtype: int64

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
X = df.drop("Water_Quality", axis=1)
y = df["Water_Quality"]

In [49]:
X = df.drop("Water_Quality", axis=1)
X.columns

Index(['pH', 'Turbidity', 'Dissolved_Oxygen', 'Conductivity', 'Nitrate',
       'Phosphate', 'Temperature', 'TDS'],
      dtype='object')

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42,stratify=y)

In [34]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [36]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [37]:
y_pred = model.predict(X_test_scaled)

In [38]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9275

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.94      0.98      0.96       349
           2       0.68      0.46      0.55        37

    accuracy                           0.93       400
   macro avg       0.87      0.79      0.82       400
weighted avg       0.92      0.93      0.92       400


Confusion Matrix:
 [[ 13   1   0]
 [  0 341   8]
 [  0  20  17]]


In [39]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
}).sort_values(by="Coefficient", ascending=False)

print(feature_importance)

            Feature  Coefficient
1         Turbidity     4.062137
5         Phosphate     0.743560
7               TDS     0.379934
4           Nitrate     0.203627
6       Temperature    -0.036127
2  Dissolved_Oxygen    -0.060279
0                pH    -0.189995
3      Conductivity    -0.232465


In [40]:
import joblib

joblib.dump(model, "water_quality_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [41]:
import gradio as gr

In [56]:
import gradio as gr
import joblib
import numpy as np

# Load model and scaler
model = joblib.load("water_quality_model.pkl")
scaler = joblib.load("scaler.pkl")

# Class label mapping
QUALITY_LABELS = {
    0: "Bad",
    1: "Good",
    2: "Excellent"
}

def predict_water_quality(
    ph,
    turbidity,
    dissolved_oxygen,
    conductivity,
    nitrates,
    phosphates,
    temperature,
    TDS
):
    try:
        input_data = np.array([[
            float(ph),
            float(turbidity),
            float(dissolved_oxygen),
            float(conductivity),
            float(nitrates),
            float(phosphates),
            float(temperature),
            float(TDS)
        ]])

        # Scale input
        input_scaled = scaler.transform(input_data)

        # Predict class
        pred_class = model.predict(input_scaled)[0]

        # Convert numeric class to label
        quality_label = QUALITY_LABELS.get(pred_class, "Unknown")

        return f"Predicted Water Quality: {quality_label}"

    except Exception as e:
        return f"Error: {str(e)}"

# Gradio Interface
app = gr.Interface(
    fn=predict_water_quality,
    inputs=[
        gr.Number(label="pH", value=7.0),
        gr.Number(label="Turbidity (NTU)", value=5.0),
        gr.Number(label="Dissolved Oxygen (mg/L)", value=6.0),
        gr.Number(label="Conductivity (µS/cm)", value=300),
        gr.Number(label="Nitrates (mg/L)", value=10),
        gr.Number(label="Phosphates (mg/L)", value=0.5),
        gr.Number(label="Temperature (°C)", value=25),
        gr.Number(label="TDS (mg/L)", value=500),
    ],
    outputs=gr.Textbox(label="Result"),
    title="Water Quality Prediction",
    description="Enter water parameters to classify water quality as Bad, Good, or Excellent."
)

if __name__ == "__main__":
    app.launch()

* Running on local URL:  http://127.0.0.1:7865
* To create a public link, set `share=True` in `launch()`.


c:\Users\muham\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
